import type { SparePart } from '../types/sparePart';

export const placeholderParts: SparePart[] = [
  {
    id: '1',
    name: 'Engine Oil Filter',
    category: 'Engine',
    carMake: 'Toyota',
    carModel: 'Camry',
    carYear: '2020',
    condition: 'new',
    price: 45000,
    stockQuantity: 12,
    imageUrl: 'https://placehold.co/400x300/0F172A/F59E0B?text=SpareIQ',
    description: 'Original Toyota engine oil filter for Camry 2020 model',
    createdAt: '2026-05-15T10:30:00Z',
  },
  {
    id: '2',
    name: 'Brake Pads Set',
    category: 'Brakes',
    carMake: 'Honda',
    carModel: 'Civic',
    carYear: '2019',
    condition: 'tokunbo',
    price: 85000,
    stockQuantity: 8,
    imageUrl: 'https://placehold.co/400x300/0F172A/F59E0B?text=SpareIQ',
    description: 'High quality brake pads set for Honda Civic',
    createdAt: '2026-05-14T14:20:00Z',
  },
  {
    id: '3',
    name: 'Alternator',
    category: 'Electrical',
    carMake: 'Mercedes',
    carModel: 'C-Class',
    carYear: '2018',
    condition: 'tokunbo',
    price: 225000,
    stockQuantity: 3,
    imageUrl: 'https://placehold.co/400x300/0F172A/F59E0B?text=SpareIQ',
    description: 'Mercedes-Benz alternator in excellent condition',
    createdAt: '2026-05-13T09:45:00Z',
  },
  {
    id: '4',
    name: 'Shock Absorber',
    category: 'Suspension',
    carMake: 'Kia',
    carModel: 'Sportage',
    carYear: '2021',
    condition: 'new',
    price: 156000,
    stockQuantity: 6,
    imageUrl: 'https://placehold.co/400x300/0F172A/F59E0B?text=SpareIQ',
    description: 'Original Kia shock absorber for Sportage SUV',
    createdAt: '2026-05-12T16:15:00Z',
  },
  {
    id: '5',
    name: 'Front Door Handle',
    category: 'Body Parts',
    carMake: 'Hyundai',
    carModel: 'Elantra',
    carYear: '2020',
    condition: 'new',
    price: 35000,
    stockQuantity: 15,
    imageUrl: 'https://placehold.co/400x300/0F172A/F59E0B?text=SpareIQ',
    description: 'Hyundai Elantra front door handle in chrome',
    createdAt: '2026-05-11T11:30:00Z',
  },
  {
    id: '6',
    name: 'Radiator',
    category: 'Cooling System',
    carMake: 'Toyota',
    carModel: 'Hilux',
    carYear: '2017',
    condition: 'tokunbo',
    price: 195000,
    stockQuantity: 2,
    imageUrl: 'https://placehold.co/400x300/0F172A/F59E0B?text=SpareIQ',
    description: 'Cooling radiator for Toyota Hilux pickup truck',
    createdAt: '2026-05-10T13:00:00Z',
  },
  {
    id: '7',
    name: 'Starter Motor',
    category: 'Engine',
    carMake: 'Honda',
    carModel: 'Accord',
    carYear: '2019',
    condition: 'new',
    price: 125000,
    stockQuantity: 5,
    imageUrl: 'https://placehold.co/400x300/0F172A/F59E0B?text=SpareIQ',
    description: 'Honda Accord starter motor with warranty',
    createdAt: '2026-05-09T08:45:00Z',
  },
  {
    id: '8',
    name: 'Battery',
    category: 'Electrical',
    carMake: 'Mercedes',
    carModel: 'E-Class',
    carYear: '2021',
    condition: 'tokunbo',
    price: 350000,
    stockQuantity: 0,
    imageUrl: 'https://placehold.co/400x300/0F172A/F59E0B?text=SpareIQ',
    description: 'Premium vehicle battery for Mercedes E-Class',
    createdAt: '2026-05-08T15:20:00Z',
  },
];
